### ISSUE TITLE
NoticeIcon API 设计

### ISSUE THREAD

**Issue by Amanda111** [uxcore/uxcore-notice-icon#1]
## Props

| Name | Type | Required | Default | Comments |
|---|---|---|---|---|
|icon|string|optional|xiaoxitixingfull| 通知图标; http://uxco.re/components/icon/|
|dot|boolean|optional|false|是否显示通知数量；默认不展示数字，只有一个小红点|
|count|number|optional|-|通知的数量|
|overflowCount|number|optional|99|通知封顶的数字|
|trigger|string|optional|hover|trigger mode：'hover' or 'click'|
|noticeTitle|string|optional|通知|通知标题|
|emptyIcon|string|optional|默认图标|其他可选：'access_restriction','acitve_empty','request_error','search_empty','unknown_error';http://uxco.re/components/icon/|
|emptyText|string|optional|暂无数据|占位文字|
|topActionText|string|optional|操作|右上角操作提示文字，如“清空”操作|
|onTopActionClick|function|optional|-|点击右上角操作的回调|
|actionBarText|string|optional|操作|底部操作提示文字，“查看”操作|
|onActionBarClick|function|optional|-|点击底部操作的回调|
|onVisibleChange|function|optional|fuction(visible)|显隐状态的回调

**Comment by eternalsky** [comment]
noticeTitle --> title，既然已经是在 noticeIcon 里了，就不用再提 notice。
topActionText 和 onTopActionClick 合并成 extra，extra 允许是 React element，回调可以绑在 element 上。
其他 ok。

**Comment by Amanda111** [comment]
#### Update

---

| Name | Type | Required | Default | Comments |
|---|---|---|---|---|
|title|string|optional|通知|通知标题|
|topAction|React Element|optional|-|右上角操作|
|actionBar|object \| render function|optional|-|支持默认\*和自定义形式|

\*
如果propTypes为object则使用默认样式渲染，object需按如下定义

```js
{
    "text": string,
    "action": function
}
```

**Comment by eternalsky** [comment]
ok
